export const Routes = {
    LOGIN: 'Login',
    REGISTER: 'register',
    RECUPERAR: 'recuperar',
    VALIDAR: 'validar',
    RESET: 'reset',
    HOME: 'Home',
    PRINCIPAL: 'Principal',
    CARNET: 'Carnet',
    QR: 'Qr',
    SCANQR: 'ScanQr',
    SEARCH: 'search',
    ESCANEAR: 'Escanear',
    GENERAR: 'Generar',
    PROFILE: 'Profile',
    INVITACION: 'Invitacion',
    FAMILIARES: 'Familiares',
    ENTRADAS: 'Entradas',
    ENTRADAS_INVITADO: 'Entradas-invitado',
    EVENTOS: 'Eventos',
    SOLICITUDES: 'Solicitudes',
    CREAR_SOLICITUD: 'Crear-solicitud',
    DETALLE_SOLICITUD: 'Detalle-solicitud',
    RESERVAS: 'Reservas',
    RESERVAR: 'Reservar',
    ENCUESTAS: 'Encuestas',
    ENCUESTA: 'Encuesta',
}

export const servidorBack = "https://www.apiclubsincelejo.prismau.co";