export const Routes = {
    LOGIN: '/',
    REGISTER: '/register',
    HOME: 'Home',
    PRINCIPAL: 'Principal',
    CARNET: 'Carnet',
    QR: 'Qr',
    SCANQR: 'ScanQr',
    SEARCH: 'search',
    ESCANEAR: 'Escanear',
    GENERAR: 'Generar',
    PROFILE: 'Profile',
    INVITACION : 'Invitacion',
    FAMILIARES : 'Familiares',
    ENTRADAS : 'Entradas',
    EVENTOS : 'Eventos',
    SOLICITUDES : 'Solicitudes',
    CREAR_SOLICITUD : 'Crear-solicitud',
    DETALLE_SOLICITUD : 'Detalle-solicitud',
    RESERVAS : 'Reservas',
    RESERVAR : 'Reservar',
    ENCUESTAS : 'Encuestas',
    ENCUESTA: 'Encuesta',
}

export const servidorBack = "https://www.apiclubsincelejo.prismau.co";